// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYcWKx7wXmPqBIyNrJ_DDainmMSdW4QF8',
    appId: '1:783640941271:web:1d6413cac4ac346f38d692',
    messagingSenderId: '783640941271',
    projectId: 'scan-ktm',
    authDomain: 'scan-ktm.firebaseapp.com',
    storageBucket: 'scan-ktm.firebasestorage.app',
    measurementId: 'G-T81FG91LN5',
    databaseURL:
        'https://scan-ktm-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs8joSVOJTM_3S93F6pTOc3vyERJ7mjb0',
    appId: '1:783640941271:android:46ee22d68cc47cf038d692',
    messagingSenderId: '783640941271',
    projectId: 'scan-ktm',
    storageBucket: 'scan-ktm.firebasestorage.app',
    databaseURL:
        'https://scan-ktm-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKwsFSSxU4PwgPc5sZhVOxwGl5wH8yTRw',
    appId: '1:783640941271:ios:7d3de890249ca04638d692',
    messagingSenderId: '783640941271',
    projectId: 'scan-ktm',
    storageBucket: 'scan-ktm.firebasestorage.app',
    iosBundleId: 'com.example.stnkCheckUad',
    databaseURL:
        'https://scan-ktm-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKwsFSSxU4PwgPc5sZhVOxwGl5wH8yTRw',
    appId: '1:783640941271:ios:7d3de890249ca04638d692',
    messagingSenderId: '783640941271',
    projectId: 'scan-ktm',
    storageBucket: 'scan-ktm.firebasestorage.app',
    iosBundleId: 'com.example.stnkCheckUad',
    databaseURL:
        'https://scan-ktm-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYcWKx7wXmPqBIyNrJ_DDainmMSdW4QF8',
    appId: '1:783640941271:web:8cda45cdd55d9f2838d692',
    messagingSenderId: '783640941271',
    projectId: 'scan-ktm',
    authDomain: 'scan-ktm.firebaseapp.com',
    storageBucket: 'scan-ktm.firebasestorage.app',
    measurementId: 'G-W1SRP7JWSN',
    databaseURL:
        'https://scan-ktm-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}
